//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stktakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductStocks = new HashSet<ProductStocks>();
        }

        
        public short ProductId { get; set; }
        [Display(Name ="Ürün Adý")]
        [Required(ErrorMessage = "Zorunludur")]
        public string ProductName { get; set; }
        [Display(Name ="Marka")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Brands { get; set; }
        [Display(Name ="Kategori Adý")]
        [Required(ErrorMessage = "Zorunludur")]
        public Nullable<short> CategorieName { get; set; }
        [Display(Name ="Ürün Tipi")]
        [Required(ErrorMessage = "Zorunludur")]
        public string ProductType { get; set; }
        [Display(Name ="Alýþ Fiyatý")]
        [Required(ErrorMessage = "Zorunludur")]
        public Nullable<decimal> BuyingPrice { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStocks> ProductStocks { get; set; }
    }
}
