//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stktakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductStocks
    {
        public short UrunStokId { get; set; }
        [Display(Name ="Adet")]
        [Required(ErrorMessage = "Zorunludur")]
        public Nullable<int> Piece { get; set; }
        [Display(Name ="Kayýt Tarihi")]
        [Required(ErrorMessage ="Zorunludur")]
        public Nullable<System.DateTime> RecordDate { get; set; }
         [Display(Name ="Urun Adý")]
        [Required(ErrorMessage = "Zorunludur")]
        public short ProductId { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
