//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stktakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public short UserId { get; set; }
        [Display(Name ="Adý")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Name { get; set; }
        [Display(Name = "Soyadý")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Surname { get; set; }
        [Display(Name = "TakmaAdý")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Nickname { get; set; }
        [Display(Name = "Þifre")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Password { get; set; }
        [Display(Name = "Numara")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Number { get; set; }
        [Display(Name = "EPosta")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Email { get; set; }

        public Nullable<System.DateTime> DateOfRegistrion { get; set; }
    }
}
